#
# Module manifest for module 'HCBotScenarioIE'
#
# Generated by: evgrigor
#
# Generated on: 04/01/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'HCBotScenarioIE.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '7dd6950c-9604-48fe-a5cd-ac2eab85dcb2'

# Author of this module
Author = 'Evgeny Grigorenko'

# Company or vendor of this module
CompanyName = 'Microsoft'

# Copyright statement for this module
Copyright = '(c) Microsoft. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This PowerShell module allows you to import and export Health Bot scenarios. Through integration into existing SCS/DevOps tools it provides tracking and versioning capabilities for scenarios as well as unlock some DevOps practices for bot developers.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-HCBScenario', 'Set-HCBScenario'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

}