###############################################################################
#
# Continuous Improvement/Continuous Deployment Pipeline
#
###############################################################################

name: CI/CD Pipeline

on:
  # Execute on pushes to master branch.
  push:
    # branches: 
    #   - master
    # # The push must include changes to Scenarios.
    # paths:
    #   - "Scenarios/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      scenariosFilePath: ${{ './Scenarios' }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Import Scenarios in source to the bot instance.
      - name: Import HCB Scenarios.
        run: |
          Import-Module -Name ./Scripts/ScenarioImportExport/HCBotScenarioIE/;
          Set-HCBScenario -FromFolder ${{ env.scenariosFilePath }} -Tenant ${{ secrets.PROD_TENANT_NAME }} -JwtSecret ${{ secrets.PROD_JWT_SECRET }} -InformationAction Continue;
        shell: pwsh



