###############################################################################
#
# Develop Continuous Improvement Pipeline
#
###############################################################################

name: Develop CI Pipeline

on:
  # Execute on pushes to develop branch.
  push:
    # branches: [ develop ]
    # The push must include changes to Scenarios.
    # - "scenarios/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      scenariosFilePath: ${{ 'scenarios/**' }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



